development:
  adapter: mysql
  database: geonames
  host: localhost
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql
  database: geonames_test
  host: localhost
  username: root
  password:
  encoding: utf8
# 
# production:
#   adapter: mysql
#   database: kicker_stats_production
#   host: localhost
#   username: root
#   password:
#   encoding: utf8
